### ISSUE TITLE
MANIFEST.in should include fixtures/*

### ISSUE THREAD

**Issue by spikergit1** [mk-fg/feedjack#3]
Upon executing manage.py migrate,

    IOError: [Errno 2] No such file or directory: u'feedjack/venv/local/lib/python2.7/site-packages/feedjack/fixtures/migration_data_0005.json'

It appears that fixtures is not included in the deployed package.  I think should be added to MANIFEST.in

**Comment by mk-fg** [comment]
Indeed it was missing there, my bad.
Should be fixed now.

Thanks!
