### ISSUE TITLE
when posted on heroku it redirects to 127.0.0.1:8000

### ISSUE THREAD

**Issue by michalstepniewski** [mk-fg/feedjack#6]
when posted on heroku it redirects to 127.0.0.1:8000

**Comment by mk-fg** [comment]
Can happen due to misconfiguration (feedjack site added as `http://127.0.0.1:8000`), but I don't know how stuff works on heroku, and never tested the app there, so can be something else entirely.
In any case, not likely to look into it myself, unfortunately.

**Comment by michalstepniewski** [comment]
Hello,
How can I reconfigure the site so that feedjack site is added properly? In the settings.py file?

**Comment by mk-fg** [comment]
You can add/remove sites via Django admin app.
Can also admin feeds and such there, some management commands are also available for these.

My memory is a bit fuzzy (haven't touched this project in a while), but iirc on first request to feedjack, initial site should be added automatically, which I think might be a problem if heroku does some "ping" request from localhost.

See also: https://github.com/mk-fg/feedjack/#configuration
I think that section is a copy-pasted bit from old feedjack.org, which is now likely to be only available through archive.org wayback machine, but maybe had more such info.
